/* Creative data for the 12 short-form video packages. Edit here, then run generate.mjs. */

export const GLOBAL = {
  characters: {
    Maya: 'Maya: woman late 20s, medium-brown shoulder-length hair half-tied, warm olive skin with natural texture and light freckles, small silver stud earrings.',
    Danh: 'Danh: man early 30s, short black hair, light stubble, rectangular acetate glasses.',
    none: '',
  },
  environments: {
    'Creator desk': 'home office corner: ring light half in frame, phone tripod, open laptop, slightly dying plant, warm window daylight camera-left',
    'Living room studio': 'couch and rug, morning light, visible cable mess at frame edge',
    'Kitchen': 'worn timber bench, real steam, overhead practical lamp',
    'Gym corner': 'garage gym, daylight roller door, chalk dust, no neon',
  },
  camera: {
    'LOCKED': 'static tripod shot, no camera movement',
    'HANDHELD-CALM': 'gentle handheld sway, documentary feel, no walking',
    'PUSH-IN-SLOW': 'slow push-in toward subject, 5–8% zoom over the shot, ease-in-out',
    'OVERHEAD-LOCK': 'top-down locked shot, 90 degrees, hands and surface',
    '3Q-SWITCH': 'three-quarter side angle, locked tripod',
    'INSERT-MACRO': 'close macro insert, shallow depth of field',
    'WHIP-PAN': 'fast whip pan following the subject’s head-turn, natural motion blur',
  },
  defaultLight: 'soft window daylight key from camera-left, warm lamp fill, lifted blacks',
};

export const videos = [

{
  slug: 'day-01-reel-autopsy', day: 1, title: 'The Reel that died at 212 views',
  duration: 34, aspect: '9:16', character: 'Maya', environment: 'Creator desk', wardrobe: 'rust-orange tee',
  objective: 'Reach + pain recognition; establish the signature autopsy format',
  audience: 'creators', funnel: 'TOFU', successMetric: '3s hold >70%; 1k+ accounts reached',
  promise: 'See the exact second a Reel dies, and why, in 34 seconds.',
  abHook: 'Your Reel didn’t flop. It flopped at second two — here’s proof.',
  rationale: 'The autopsy is the brand’s signature format: a visible corpse (dead Reel), a timestamp of death, a mechanism, a fix. It demonstrates the product’s core value (the why) without showing the product at all — pure craft authority on day one.',
  perfDefault: 'conversational, forensic relish without smugness',
  voNotes: 'Dry, matter-of-fact, like a friend showing you something fascinating. No tragedy voice — flops are normal here.',
  beats: [
    { t: [0, 2.5], vo: 'This Reel died at two hundred and twelve views.', os: 'died at 212 views',
      visual: 'Maya at desk holds her phone toward camera, screen dark (real screen composited in edit)', action: 'taps the phone once against the desk edge, deadpan', cam: 'HANDHELD-CALM', comp: 'medium close-up, eye level, phone in lower third', negs: ['NEG-PHONE-UI'], editNote: 'audio: single dry tap foley with VO onset' },
    { t: [2.5, 7], vo: 'Not because the content was bad. Because of one second. This one.', os: 'one second killed it',
      visual: 'Maya leans in, raises an eyebrow, holds up one finger', action: 'single finger raise, slight head tilt', cam: 'LOCKED', comp: 'medium close-up, eye level' },
    { t: [7, 14], vo: 'Second two. The intro animation is still playing. Nothing has moved. Nothing has been promised. The viewer’s thumb is already gone.', os: '0:02 — nothing has happened yet',
      visual: 'Maya mimes a slow thumb-scroll in the air, then lets her hand drop', action: 'air-scroll gesture, hand drop, small shrug', cam: 'LOCKED', comp: 'medium shot, eye level', negs: ['NEG-PHONE-UI'] },
    { t: [14, 21], vo: 'A retention curve doesn’t slope when this happens. It cliffs. Most of the audience gone before the content started.', os: 'it doesn’t slope. it cliffs.',
      visual: 'Maya draws a sharp cliff shape in the air with one hand, following it with her eyes', action: 'decisive downward hand motion tracing a cliff', cam: '3Q-SWITCH', comp: 'medium shot, three-quarter angle — chapter change' },
    { t: [21, 28], vo: 'The fix costs nothing. Open mid-action. Put the promise on screen inside the first second. Save the branding for the end card.', os: 'open mid-action · promise by 0:01',
      visual: 'Maya counts the three fixes on her fingers, energy lifting', action: 'three-count on fingers, forward lean', cam: 'PUSH-IN-SLOW', comp: 'medium close-up tightening', perf: 'energy lifts — the useful part' },
    { t: [28, 34], vo: 'Tomorrow I’ll show you the five ways Reels die in their first three seconds. Follow so you don’t miss the autopsy.', os: 'daily teardowns → follow',
      visual: 'Maya settles back, half-smile, glances at the plant, back to lens', action: 'settle back, direct address', cam: 'LOCKED', comp: 'medium shot, eye level' },
  ],
  qcRisks: ['Hands: finger-count beat (shot 5) and air-scroll (shot 3) — inspect every frame', 'Phone screen must stay dark for compositing', 'Face consistency across the 3Q angle switch'],
  thumb: { concept: 'Framegrab of shot 2 (eyebrow raise, finger up) with heavy scrim', text: '212 views. one second.', source: 'framegrab shot 2', prompt: '' },
  extraRefs: ['Real screen-recording of a paused Reel UI for the edit composite (record from own account — 20s)'],
},

{
  slug: 'day-03-posting-time-myth', day: 3, title: 'Posting time is mostly noise',
  duration: 32, aspect: '9:16', character: 'Maya', environment: 'Creator desk', wardrobe: 'grey hoodie',
  objective: 'Shares + differentiation from scheduler-tool advice',
  audience: 'creators', funnel: 'TOFU', successMetric: 'Share rate >1%',
  promise: 'Permission to stop agonising over posting time — and the thing to obsess over instead.',
  abHook: 'Everyone blames the algorithm. The data blames your first second.',
  rationale: 'Attacks the most over-taught, lowest-leverage advice in the niche. Contradiction hooks travel; the reframe (first-second > schedule) is our category position in one video.',
  perfDefault: 'warm contrarian — kind about the people, ruthless about the advice',
  voNotes: 'Confident, a little wry. This is a “put the burden down” video, not a lecture.',
  beats: [
    { t: [0, 3], vo: 'Posting time didn’t kill your Reel. Your first zero point eight seconds did.', os: 'it’s not WHEN you post',
      visual: 'Maya mid-gesture pushing a phone face-down on the desk', action: 'pushes phone face-down, looks up at lens', cam: 'HANDHELD-CALM', comp: 'medium close-up, eye level, hands visible on desk', negs: ['NEG-PHONE-UI'] },
    { t: [3, 9], vo: 'Creators A-B test six o’clock against seven o’clock like it’s science. Meanwhile the hook was decided in thirty seconds at the end of the edit.', os: '6:03pm vs 7:03pm ≠ strategy',
      visual: 'Maya mimes flipping between two options with both hands, mock-serious face', action: 'two-handed either-or gesture, small eye-roll at herself', cam: 'LOCKED', comp: 'medium shot' },
    { t: [9, 16], vo: 'Distribution systems feed content to a test audience whenever you post. What decides the next wave isn’t your clock. It’s whether that audience stops scrolling.', os: 'the test audience decides. not the clock.',
      visual: 'Maya explains with open palms, then snaps fingers on “stops”', action: 'open-palm explain, single finger snap', cam: '3Q-SWITCH', comp: 'three-quarter medium — chapter change' },
    { t: [16, 24], vo: 'So the honest hierarchy: first second, then payoff, then save-worthiness. Posting time is a rounding error unless you’re posting at three a.m.', os: '1st second > payoff > save-worthy >>> clock',
      visual: 'Maya stacks her hands in levels from top to bottom on each item', action: 'hand-stack hierarchy gesture, deliberate', cam: 'PUSH-IN-SLOW', comp: 'medium close-up tightening' },
    { t: [24, 32], vo: 'Send this to the friend who has a spreadsheet of posting times. They’re free now. Tomorrow: what a working first second actually contains.', os: 'free the spreadsheet friend → share',
      visual: 'Maya laughs briefly, then settles into direct address', action: 'genuine short laugh, settle, direct look', cam: 'LOCKED', comp: 'medium shot, eye level' },
  ],
  qcRisks: ['Finger snap frame (shot 3) — hand check', 'Hoodie consistency (not the day-1 tee)', 'Laugh in shot 5 must read genuine, not uncanny'],
  thumb: { concept: 'Framegrab shot 1: phone pushed face-down, Maya’s look up', text: 'it’s not when you post', source: 'framegrab shot 1', prompt: '' },
},

{
  slug: 'day-05-hook-time-pov', day: 5, title: '3 hours editing, 30 seconds on the hook',
  duration: 24, aspect: '9:16', character: 'Maya', environment: 'Living room studio', wardrobe: 'rust-orange tee',
  objective: 'Pain recognition + comment bait (honest kind)',
  audience: 'creators', funnel: 'TOFU', successMetric: 'Comment rate >0.8%',
  promise: 'Being seen. The mirror video.',
  abHook: 'The part of your Reel you spend the least time on decides the most.',
  rationale: 'Pure identity-mirror from the customer language bank. Short, cheap, high comment probability (“guilty”). Sets up day 16’s hook-anatomy educational payoff.',
  perfDefault: 'self-deprecating warmth — we are all this person',
  voNotes: 'Playful, rueful. The laugh is at ourselves, with love.',
  beats: [
    { t: [0, 3], vo: 'POV: you spent three hours editing and thirty seconds on the thing that decides everything.', os: '3 hrs editing. 30 sec on the hook.',
      visual: 'Maya slumped into couch corner, laptop balanced, the thousand-yard editing stare', action: 'slow blink, exhale, doesn’t move otherwise', cam: 'LOCKED', comp: 'medium wide, couch frame, slightly low angle' },
    { t: [3, 9], vo: 'Colour grade: forty minutes. Sound design: an hour. The captions kerning — the kerning —', os: 'the KERNING',
      visual: 'Quick punch-in as Maya gestures increasingly precisely at invisible details', action: 'pinched-fingers precision gestures, escalating', cam: 'LOCKED', comp: 'punch-in to close-up (edit punch, not camera)', editNote: 'PUNCH-IN cut at 3.0s' },
    { t: [9, 16], vo: 'And then, exporting at midnight: “eh, I’ll just open with a wave and my name.” Three hours, decided in second one.', os: '“…I’ll just open with a wave”',
      visual: 'Maya mimes a limp little wave, then stares into the middle distance as realisation lands', action: 'limp wave, freeze, slow horror', cam: 'LOCKED', comp: 'close-up' },
    { t: [16, 24], vo: 'Flip the ratio once. Thirty minutes on the first second, and the hours you already spend finally get seen. Comment “guilty” — you’re safe here.', os: 'comment “guilty” 🫡',
      visual: 'Maya sits up, points at the lens on “flip”, ends open-palmed and warm', action: 'sit up, single point, open palms', cam: 'PUSH-IN-SLOW', comp: 'medium close-up' },
  ],
  qcRisks: ['The limp wave (shot 3) — hand check hardest here', 'Couch slump posture must read tired-real, not ragdoll', 'Living room continuity (not the desk set)'],
  thumb: { concept: 'Framegrab shot 3: the limp wave mid-frame', text: '3 hrs. then this.', source: 'framegrab shot 3', prompt: '' },
},

{
  slug: 'day-08-retention-desert', day: 8, title: 'The 18-second desert',
  duration: 38, aspect: '9:16', character: 'Maya', environment: 'Creator desk', wardrobe: 'grey hoodie',
  objective: 'Saves; introduce retention-shape thinking',
  audience: 'creators + SMMs', funnel: 'TOFU', successMetric: 'Save rate >2%',
  promise: 'A named, findable, fixable pattern — the desert.',
  abHook: 'Your hook isn’t the problem. Second 14 to 32 is the problem.',
  rationale: 'Names a failure pattern people recognise instantly but couldn’t articulate. Naming things builds authority; “desert” is sticky vocabulary that markets itself in comments.',
  perfDefault: 'teacher energy, concrete and generous',
  voNotes: 'Clear and structured; slow slightly through the three desert-breakers so they land as a list.',
  beats: [
    { t: [0, 3.5], vo: 'This Reel has a great hook, a strong ending, and an eighteen-second desert in the middle where everyone left.', os: 'the 18-second desert',
      visual: 'Maya frames a wide empty gap between her two hands, staring into it', action: 'hands spread the gap, eyes into the void between them', cam: 'HANDHELD-CALM', comp: 'medium close-up, hands mid-frame' },
    { t: [3.5, 10], vo: 'The desert: one locked shot, one energy level, no new information for eighteen seconds. Viewers don’t leave because it’s bad. They leave because nothing signals that staying pays.', os: 'nothing signals that staying pays',
      visual: 'Maya goes deliberately still and monotone-faced for a beat, mimicking the desert, then breaks it', action: 'freeze-face beat, then snap back to life', cam: 'LOCKED', comp: 'medium shot', perf: 'the freeze-beat is the joke — commit to it' },
    { t: [10, 18], vo: 'Deserts hide in talking-head stories, in cooking mid-sections, in “step two” of every tutorial. The tell: you can scrub ten seconds and miss nothing.', os: 'the tell: scrub 10s, miss nothing',
      visual: 'Maya mimes scrubbing a timeline in the air, checks an imaginary watch, shrugs', action: 'air-scrub, watch-check, shrug', cam: '3Q-SWITCH', comp: 'three-quarter medium' },
    { t: [18, 28], vo: 'Three desert-breakers. Move a reveal into the middle. Change the frame — angle, insert, text — every four seconds. Or just cut it. Forty seconds of good beats sixty with a desert.', os: '① mid-reveal ② new frame every 4s ③ cut it',
      visual: 'Maya counts three on fingers, each with a distinct decisive gesture', action: 'three-count, each finger a beat', cam: 'PUSH-IN-SLOW', comp: 'medium close-up tightening' },
    { t: [28, 38], vo: 'Save this, then scrub your last three posts and find the desert. It’s there. Mine was twenty-two seconds long and I defended it at the time.', os: 'save → then go find yours',
      visual: 'Maya raises a hand in mock confession on the last line, half-smile', action: 'confession hand-raise, settle', cam: 'LOCKED', comp: 'medium shot' },
  ],
  qcRisks: ['Three-count fingers (shot 4)', 'The freeze-beat (shot 2) must look intentional, not a generation glitch — brief mid-shot stillness is unusual for video models; may need 2 takes cut together', 'Hoodie lock'],
  thumb: { concept: 'Framegrab shot 1: hands framing the gap', text: 'the 18-second desert', source: 'framegrab shot 1', prompt: '' },
},

{
  slug: 'day-10-before-after', day: 10, title: 'Same Reel, one fix, watch',
  duration: 40, aspect: '9:16', character: 'Maya', environment: 'Creator desk', wardrobe: 'rust-orange tee',
  objective: 'Product curiosity via visible proof-of-craft; source footage for day-30 cutdown',
  audience: 'creators', funnel: 'MOFU', successMetric: 'Profile visits; demo page visits',
  promise: 'Watch the first second decide everything, twice.',
  abHook: 'We re-cut one Reel’s first 2 seconds. Here’s the before and after.',
  rationale: 'The month’s highest-production-value asset: a visible A/B of the same content. Nothing sells “the first second decides” like watching both versions. All numbers demo-labelled.',
  compliance: 'The before/after scores shown are demo data from our example analysis, labelled on-screen “example data”. No real account results are claimed or implied.',
  perfDefault: 'showman restraint — let the split screen do the talking',
  voNotes: 'Minimal VO; the video carries it. Land the numbers cleanly.',
  beats: [
    { t: [0, 3], vo: 'Same Reel. One change. Watch the first three seconds decide everything, twice.', os: 'same reel. one fix. watch.',
      visual: 'Maya holds up two fingers, then gestures to both sides of the frame as if presenting two panels', action: 'two-finger raise, symmetrical both-sides gesture', cam: 'LOCKED', comp: 'centred medium close-up, symmetrical framing' },
    { t: [3, 12], vo: 'Version one. Logo … then a hello … the content starts at second four.', os: 'BEFORE — content starts at 0:04 (example data)',
      visual: 'Split-screen composite placeholder: left panel plays the “before” example cut (composited in edit from example footage), Maya watches from right panel, unimpressed', action: 'Maya side-eyes the left panel, checks nails', cam: 'LOCKED', comp: 'split screen: 60% example panel left, 40% Maya right', negs: ['NEG-PHONE-UI'], editNote: 'left panel composited in edit; generate Maya panel only' },
    { t: [12, 20], vo: 'Version two. Mid-action first frame, promise on screen at zero point six. Same footage. Reordered.', os: 'AFTER — promise at 0:00.6 (example data)',
      visual: 'Split-screen: right-panel Maya now leans in, engaged, small nod at the after-cut playing left', action: 'lean-in, engaged nod', cam: 'LOCKED', comp: 'same split geometry — continuity with previous shot' },
    { t: [20, 30], vo: 'In our example analysis the hook score moved from forty-one to eighty-four. Not because the content changed. Because the first second finally showed it.', os: 'hook 41 → 84 (example data)',
      visual: 'Maya full-frame again, draws the number jump in the air with one rising hand', action: 'rising hand arc on the number move', cam: 'PUSH-IN-SLOW', comp: 'medium close-up tightening' },
    { t: [30, 40], vo: 'Every Reel has a version-two hiding in the footage you already shot. The method for finding it is in my bio. Or just steal the rule: nothing before the promise.', os: 'rule: nothing before the promise',
      visual: 'Maya taps her temple, then points down-left toward bio position, relaxed', action: 'temple tap, bio point, settle', cam: 'LOCKED', comp: 'medium shot' },
  ],
  qcRisks: ['Split-screen shots: generate Maya’s panel only; example-cut panels are edited in — do NOT generate fake UI or fake footage of “a real account”', 'The rising-arc hand (shot 4)', 'Symmetry of framing across shots 2–3 for the split continuity'],
  thumb: { concept: 'Split thumbnail: dim left frame vs vivid right frame, big arrow', text: '41 → 84', source: 'composited from shots 2–3 framegrabs', prompt: '' },
  extraRefs: ['Two 8-second example cuts (before/after) built from the day-1 example concept — edit assets, not generations'],
},

{
  slug: 'day-12-silent-process', day: 12, title: 'The silent process trend, done right',
  duration: 30, aspect: '9:16', character: 'Danh', environment: 'Kitchen', wardrobe: 'navy overshirt over white tee',
  objective: 'Trend authority; demonstrate the format while explaining it',
  audience: 'creators', funnel: 'TOFU', successMetric: 'Reach vs account baseline',
  promise: 'A rising format explained by being performed.',
  abHook: 'No voiceover. No script. Rising engagement. Here’s the catch.',
  rationale: 'Meta-content: the video IS the format it teaches. Danh cooks in silence; text overlays do the teaching. Demonstrates our trend-evidence honesty (“in accounts we track”) in public.',
  compliance: 'Trend claims are scoped honestly on-screen: “rising across accounts we track” — no global stats invented.',
  perfDefault: 'no direct address; absorbed in the task; the overlays talk',
  voNotes: 'NO VOICEOVER — ambient kitchen sound only (knife, sizzle, pour). This is the point of the format.',
  timeOfDay: 'late afternoon',
  beats: [
    { t: [0, 3], vo: '', os: 'this format is quietly winning right now',
      visual: 'Overhead: Danh’s hands slide a chopping board into frame, knife taps once — crisp real audio', action: 'board slide, single knife tap', cam: 'OVERHEAD-LOCK', comp: 'top-down, hands and timber bench', negs: ['NEG-FOOD'], audio: 'knife tap foley, room tone' },
    { t: [3, 9], vo: '', os: 'no voiceover · ambient sound · rising in accounts we track',
      visual: 'Overhead chopping rhythm, steam drifting from a pan at frame edge', action: 'steady confident chopping, natural pace', cam: 'OVERHEAD-LOCK', comp: 'top-down', negs: ['NEG-FOOD'], audio: 'real chop rhythm' },
    { t: [9, 16], vo: '', os: 'why it works: it reads as REAL against AI-voiced everything',
      visual: '3/4 shot: Danh tips vegetables into the pan, real sizzle, slight steam on glasses', action: 'pan tip, beat of satisfaction, pushes glasses up with wrist', cam: '3Q-SWITCH', comp: 'three-quarter at bench height', negs: ['NEG-FOOD'], audio: 'sizzle forward in mix' },
    { t: [16, 23], vo: '', os: 'the catch: your text hook has to do ALL the work — frame one',
      visual: 'Insert macro: wooden spoon fold, texture detail, steam', action: 'slow fold, texture visible', cam: 'INSERT-MACRO', comp: 'macro on pan contents', negs: ['NEG-FOOD'], audio: 'low simmer' },
    { t: [23, 30], vo: '', os: 'weekly trend reads, evidence attached → follow',
      visual: 'Overhead: finished bowl placed on bench, Danh’s hands withdraw, one beat of stillness', action: 'bowl place, hands out, hold', cam: 'OVERHEAD-LOCK', comp: 'top-down, bowl centred', negs: ['NEG-FOOD'], audio: 'bowl set-down, room tone', editNote: 'hold the final frame 1.5s minimum' },
  ],
  qcRisks: ['Food realism (NEG-FOOD hardest here) — no plastic gloss', 'Hands throughout — every shot is a hands shot', 'Audio is the format: foley must be sourced/recorded, not silent generations'],
  thumb: { concept: 'Overhead framegrab of shot 2 mid-chop with scrim', text: 'the silent format is winning', source: 'framegrab shot 2', prompt: '' },
},

{
  slug: 'day-16-hook-anatomy', day: 16, title: 'Anatomy of a 0.8-second hook',
  duration: 36, aspect: '9:16', character: 'Maya', environment: 'Creator desk', wardrobe: 'grey hoodie',
  objective: 'Education + saves; the week-1 promise paid off',
  audience: 'creators', funnel: 'TOFU', successMetric: 'Save rate >2%',
  promise: 'The three jobs of a first second, frame by frame.',
  abHook: 'What has to happen in your first second (frame by frame).',
  rationale: 'The core teaching asset of the month: converts our product’s hook model into free craft knowledge. Deliberately generous — the free version of what Pre-Flight automates.',
  perfDefault: 'precise, energised teacher',
  voNotes: 'Crisp. The three jobs are the spine — hit each word: MOVE, CLAIM, FACE.',
  beats: [
    { t: [0, 3], vo: 'A working hook does three jobs in under one second. Miss one, the scroll wins.', os: '3 jobs. 0.8 seconds.',
      visual: 'Maya holds up three fingers close to lens, sharp focus on hand, face soft behind', action: 'three fingers snap up, held', cam: 'LOCKED', comp: 'close-up, fingers foreground, shallow depth' },
    { t: [3, 11], vo: 'Job one: something moves. Not a logo fading in — a human, an object, a frame change. Motion is the only thing peripheral vision respects.', os: '① something MOVES',
      visual: 'Maya shoves a coffee mug across the desk; it slides through frame', action: 'decisive mug slide, eyes following it', cam: 'HANDHELD-CALM', comp: 'medium, desk surface visible' },
    { t: [11, 19], vo: 'Job two: a claim lands. On screen, not just spoken — half your viewers have sound off. Six words or fewer, readable at arm’s length.', os: '② a CLAIM lands (≤6 words)',
      visual: 'Maya holds up a hand-written card reading “your back isn’t tight. it’s this.”', action: 'card raise to chest height, steady', cam: 'LOCKED', comp: 'medium close-up, card lower third' },
    { t: [19, 27], vo: 'Job three: a face, if you have one. Eyes with intent, mid-expression — not composed and waiting. We are wired to check faces first.', os: '③ a FACE with intent',
      visual: 'Maya snaps from neutral waiting-face to animated mid-sentence expression to show the difference', action: 'the two-faces demonstration, quick switch', cam: '3Q-SWITCH', comp: 'close-up, three-quarter', perf: 'the neutral face should be comically “waiting for the take to start”' },
    { t: [27, 36], vo: 'Move, claim, face — inside zero point eight. Save this and check your last three hooks against it. The checklist version’s on screen now.', os: '✓ move ✓ claim ✓ face — by 0:00.8',
      visual: 'Maya leans back, taps the on-screen space beside her as if pinning the checklist there', action: 'lean back, screen-space tap, settle', cam: 'PUSH-IN-SLOW', comp: 'medium, negative space camera-left for checklist overlay' },
  ],
  qcRisks: ['Foreground fingers (shot 1) — highest hand risk of the month', 'Hand-written card must be legible and correctly spelled (generate card as separate insert if model garbles text — or shoot the real card on a phone)', 'The two-faces switch (shot 4) reads as intentional acting, not a glitch'],
  thumb: { concept: 'Shot 1 framegrab: three fingers to lens', text: '3 jobs. 0.8 seconds.', source: 'framegrab shot 1', prompt: '' },
  extraRefs: ['Real photographed hand-written card “your back isn’t tight. it’s this.” as edit insert fallback'],
},

{
  slug: 'day-18-worst-reel-challenge', day: 18, title: 'Send me your worst Reel',
  duration: 26, aspect: '9:16', character: 'Danh', environment: 'Creator desk', wardrobe: 'navy overshirt over white tee',
  objective: 'Comments + review pipeline (community engine)',
  audience: 'creators', funnel: 'MOFU', successMetric: 'Comments >30; submissions into review queue',
  promise: 'Free, real, public help — capacity-capped and honest about it.',
  abHook: 'Your most painful flop — I’ll find the exact second it died.',
  rationale: 'Converts audience into participants and the comment section into a teardown pipeline. The honest cap (first 30) is both operationally true and on-brand.',
  perfDefault: 'dry warmth; the challenge is friendly, not a gotcha',
  voNotes: 'Direct, unhurried. The “seriously” should feel like a hand extended, not a dare.',
  beats: [
    { t: [0, 3.5], vo: 'Send me your worst-performing Reel, and I’ll tell you why it flopped. Seriously. Worst one you’ve got.', os: 'send me your worst reel',
      visual: 'Danh beckons at the lens with two fingers, coffee mug in the other hand', action: 'two-finger beckon, sip', cam: 'HANDHELD-CALM', comp: 'medium close-up, eye level' },
    { t: [3.5, 10], vo: 'Not to roast you. Flops aren’t embarrassing — they’re data. Somewhere in those thirty seconds is one exact moment where the audience made a decision.', os: 'flops aren’t embarrassing. they’re data.',
      visual: 'Danh sets the mug down, laces fingers, leans forward — consultation mode', action: 'mug down, forward lean', cam: 'LOCKED', comp: 'medium shot' },
    { t: [10, 18], vo: 'Drop the link in the comments. I’ll reply with the second it lost people and the one change I’d make. First thirty this week — that’s a real cap, I reply by hand.', os: 'first 30 · real replies · real cap',
      visual: 'Danh points down at the comment-section space, then shows an honest palms-up “that’s the deal”', action: 'downward point, palms-up', cam: '3Q-SWITCH', comp: 'three-quarter medium' },
    { t: [18, 26], vo: 'Worst case: a stranger on the internet tells you your hook is fine and your pacing isn’t. Best case: your next post doesn’t flop. Comments. Go.', os: 'comments. go. 👇',
      visual: 'Danh sits back with a small dry smile, taps the desk twice — done talking', action: 'sit back, double desk-tap', cam: 'LOCKED', comp: 'medium shot' },
  ],
  qcRisks: ['Mug hand-off between shots 1–2 (prop continuity)', 'The beckon gesture (shot 1) — hand check', 'Danh reference consistency (first Danh desk video)'],
  thumb: { concept: 'Shot 1 framegrab: mid-beckon at lens', text: 'send me your worst reel', source: 'framegrab shot 1', prompt: '' },
},

{
  slug: 'day-20-not-luck', day: 20, title: 'Why this Reel did 3.1× (it wasn’t luck)',
  duration: 36, aspect: '9:16', character: 'Maya', environment: 'Living room studio', wardrobe: 'rust-orange tee',
  objective: 'Authority; pattern-extraction format',
  audience: 'creators', funnel: 'MOFU', successMetric: 'Profile visits',
  promise: 'Four copyable decisions behind an outlier (example data).',
  abHook: 'When a Reel outperforms there’s always a reason. Here are four.',
  rationale: 'The optimistic mirror of day 1: success has mechanics too. Reinforces the worldview (craft decides) with the same forensic voice, and demo-labels its numbers.',
  compliance: 'The 3.1× figure is example data, labelled on-screen. No real account’s results are used.',
  perfDefault: 'energised analyst — the fun kind of forensics',
  voNotes: 'Count the four decisions clearly; land “boring” with affection in the closer.',
  beats: [
    { t: [0, 3], vo: 'This Reel did three point one times the account’s average. Luck? No. Four decisions you can copy.', os: '3.1× · not luck (example data)',
      visual: 'Maya on couch edge, leaning at the lens, holds up four fingers', action: 'forward lean, four-finger raise', cam: 'HANDHELD-CALM', comp: 'medium close-up' },
    { t: [3, 11], vo: 'Decision one: it opened on the result. The finished thing, first frame. Curiosity does the rest — how did we get here?', os: '① open on the RESULT',
      visual: 'Maya spreads hands as if revealing a finished object on the coffee table', action: 'reveal gesture over table', cam: 'LOCKED', comp: 'medium, table edge in frame' },
    { t: [11, 18], vo: 'Two: it changed frames every three seconds, but the story never changed lanes. Motion without confusion.', os: '② new frame every 3s, one lane',
      visual: 'Maya chops the air in a steady rhythm — cut, cut, cut — while her other hand draws one straight line', action: 'rhythmic chops + straight-line draw, simultaneously', cam: 'LOCKED', comp: 'medium shot', perf: 'the two-hands-two-jobs bit should look slightly effortful — it’s charming' },
    { t: [18, 26], vo: 'Three: the save moment was built in — a checklist card right at peak attention. And four: the caption’s first line repeated the promise instead of saying “new post!!”', os: '③ built-in save moment ④ caption = promise',
      visual: 'Maya counts three and four on fingers, then mock-types “new post!!” in the air with disdain', action: 'finger count, air-type, single eyebrow', cam: '3Q-SWITCH', comp: 'three-quarter medium' },
    { t: [26, 36], vo: 'None of this is magic. It’s boring, repeatable structure — which is the best news possible, because you can do boring on purpose. Method in bio.', os: 'boring. repeatable. on purpose.',
      visual: 'Maya settles back with a satisfied nod, taps temple, points bio-ward', action: 'nod, temple tap, bio point', cam: 'PUSH-IN-SLOW', comp: 'medium close-up tightening' },
  ],
  qcRisks: ['Two-hands-two-jobs beat (shot 3) — the most complex hand choreography of the month; budget extra attempts or simplify to sequential', 'Four-finger counts ×2', 'Living-room continuity with day 5'],
  thumb: { concept: 'Shot 1 framegrab, four fingers up', text: '3.1×. four decisions.', source: 'framegrab shot 1', prompt: '' },
},

{
  slug: 'day-22-retention-cliff', day: 22, title: 'Find your retention cliff',
  duration: 34, aspect: '9:16', character: 'Maya', environment: 'Creator desk', wardrobe: 'grey hoodie',
  objective: 'Education + free-review pipeline',
  audience: 'creators', funnel: 'MOFU', successMetric: 'Free-review requests',
  promise: 'A do-it-today diagnostic: locate the exact second you lose people.',
  abHook: 'You’re not losing viewers evenly. You’re losing them at one exact moment.',
  rationale: 'Actionable diagnostic content that naturally hands off to the free review (“we find the cliff for you”). The product mention is one sentence, earned by ten sentences of free value.',
  perfDefault: 'practical coach; roll-up-sleeves energy',
  voNotes: 'Instructional but quick; the DIY steps must be genuinely followable from memory.',
  beats: [
    { t: [0, 3], vo: 'Every Reel has a cliff — one second where most of your viewers leave. Find it and everything changes.', os: 'every reel has a cliff',
      visual: 'Maya walks two fingers along the desk edge and drops them off it', action: 'finger-walk to the edge, drop, look up', cam: 'HANDHELD-CALM', comp: 'medium close-up, desk edge prominent' },
    { t: [3, 11], vo: 'DIY version: open your retention graph, find the steepest drop, and write down the timestamp. Not the average. The drop.', os: 'find the STEEPEST drop, not the average',
      visual: 'Maya traces a curve in the air and stabs the cliff point decisively', action: 'curve trace, point stab', cam: 'LOCKED', comp: 'medium shot', negs: ['NEG-PHONE-UI'] },
    { t: [11, 20], vo: 'Now watch your own Reel and stop at that second. What’s on screen? Nine times out of ten it’s one of three things: a lane change, a promise not yet paid, or the desert from last week.', os: 'lane change · unpaid promise · desert',
      visual: 'Maya holds up three fingers, folding one down per item', action: 'three-count folding down', cam: '3Q-SWITCH', comp: 'three-quarter medium' },
    { t: [20, 28], vo: 'Fix the cliff second before you make anything new. Repairing one post’s weakness teaches you more than shipping three more with the same one.', os: 'fix the cliff before making more',
      visual: 'Maya pulls one book from a stack and squares it carefully instead of adding more', action: 'book pull, deliberate squaring', cam: 'LOCKED', comp: 'medium, book stack on desk' },
    { t: [28, 34], vo: 'Want the cliff found for you, frame by frame, free? One Reel, full teardown — link’s in my bio.', os: 'free teardown finds it → bio',
      visual: 'Maya points bio-ward with a small honest shrug — no hard sell', action: 'bio point, shrug, half-smile', cam: 'PUSH-IN-SLOW', comp: 'medium close-up' },
  ],
  qcRisks: ['Finger-walk-and-drop (shot 1) — fine-motor hand beat', 'Book prop continuity', 'The air-curve trace must read as a graph, not vague waving'],
  thumb: { concept: 'Shot 1 framegrab: fingers at the desk edge mid-drop', text: 'find your cliff', source: 'framegrab shot 1', prompt: '' },
},

{
  slug: 'day-25-agency-why', day: 25, title: 'The client asked why, and you guessed',
  duration: 32, aspect: '9:16', character: 'Danh', environment: 'Creator desk', wardrobe: 'navy overshirt over white tee',
  objective: 'Agency segment pain + waitlist',
  audience: 'SMMs + agencies', funnel: 'MOFU', successMetric: 'Agency-segment waitlist signups',
  promise: 'The Tuesday-afternoon report scene, seen and solved.',
  abHook: 'Agency life: explaining a graph you can’t explain.',
  rationale: 'The one pure agency asset of the month (LinkedIn-primary). Mirrors the report-writing pain from discovery research; the product appears only as “the first draft written from the data”.',
  perfDefault: 'knowing, wry, colleague-to-colleague',
  voNotes: 'Dry comedy first half; genuinely useful second half. LinkedIn caption reframes in first person.',
  linkedin: 'Primary platform. Caption: first-person, no hashtags beyond #socialmedia #agencylife, ends with the waitlist link plainly.',
  beats: [
    { t: [0, 3.5], vo: 'Your client asks why engagement dropped. You write two paragraphs of educated guessing. There’s a better answer.', os: '“why did engagement drop?” “well…”',
      visual: 'Danh mid-typing, stops, stares at the screen (dark, composited), slowly removes glasses', action: 'typing stop, glasses removal, long exhale', cam: 'HANDHELD-CALM', comp: 'medium, over-shoulder angle hiding screen', negs: ['NEG-PHONE-UI'] },
    { t: [3.5, 11], vo: 'Every account manager knows the Tuesday document. “Reach softened due to, uh, seasonal factors and, um, algorithm shifts.” We’ve all shipped that sentence.', os: '“…seasonal factors and algorithm shifts”',
      visual: 'Danh air-quotes both phrases, then puts his face briefly in one hand — solidarity, not despair', action: 'double air-quotes, brief face-palm, recover', cam: 'LOCKED', comp: 'medium close-up' },
    { t: [11, 20], vo: 'But the real answer exists. It’s in the content: which hooks held, which formats earned saves, where the pacing lost people. It’s just hours of frame-by-frame work nobody billed for.', os: 'the real answer = hours nobody billed',
      visual: 'Danh gestures at an imaginary wall of clips, scrubbing through them faster and faster', action: 'wall-of-clips gesture, accelerating scrub mime', cam: '3Q-SWITCH', comp: 'three-quarter medium' },
    { t: [20, 32], vo: 'So that’s the thing we’re building for agencies: the why, written as a first draft, from the client’s own data — you edit, you own it, your logo on it. If your Tuesdays look like mine did, the waitlist is in the caption.', os: 'the “why”, drafted from the data',
      visual: 'Danh puts glasses back on, straightens, talks plainly to the lens — pitch without pitch-voice', action: 'glasses on, straighten, direct address', cam: 'PUSH-IN-SLOW', comp: 'medium close-up tightening' },
  ],
  qcRisks: ['Glasses off/on continuity across shots', 'Face-palm beat (shot 2) — hand-to-face contact is a known artefact zone', 'Screen stays dark for composite'],
  thumb: { concept: 'Shot 1 framegrab: glasses mid-removal, dead stare', text: '“why did it drop?”', source: 'framegrab shot 1', prompt: '' },
},

{
  slug: 'day-28-founding-200', day: 28, title: '200 seats, and the real reason it’s 200',
  duration: 28, aspect: '9:16', character: 'Maya', environment: 'Creator desk', wardrobe: 'rust-orange tee',
  objective: 'Founding-offer conversion with honest-scarcity positioning',
  audience: 'creators', funnel: 'BOFU', successMetric: 'Waitlist signups (150 cumulative target)',
  promise: 'A cap with a reason you can verify.',
  abHook: 'Why our beta cap is a number we can actually onboard.',
  rationale: 'The conversion asset. Its entire angle is that the scarcity is operationally real — which is both true and the sharpest differentiation available in a niche drowning in fake countdown timers.',
  compliance: 'The 200 cap and its stated reason (onboarding-call capacity) are real commitments documented in docs/24-launch-offer.md. The offer terms shown match the waitlist page exactly.',
  perfDefault: 'straight talk; the least performed video of the month',
  voNotes: 'Flat, honest, almost administrative — the tone IS the message. Half-smile allowed at “calendars”.',
  beats: [
    { t: [0, 3.5], vo: 'We’re capping our beta at two hundred people, and the reason isn’t marketing. It’s calendars.', os: '200 seats. real reason: calendars.',
      visual: 'Maya holds up a paper wall-calendar with visible pen scribbles filling the days', action: 'calendar raise, tilts it to the lens', cam: 'HANDHELD-CALM', comp: 'medium close-up, calendar readable-ish but not text-focused' },
    { t: [3.5, 11], vo: 'Every founding seat comes with a one-on-one call where we tear down your content together. Thirty minutes each. Two hundred of those is the honest limit of humans we have.', os: '200 × 30-min real calls = the cap',
      visual: 'Maya sets the calendar down, counts on fingers with a what-can-you-do shrug', action: 'calendar down, casual count, shrug', cam: 'LOCKED', comp: 'medium shot' },
    { t: [11, 19], vo: 'No countdown timer. No “only three left” that resets at midnight. Seats fill in waitlist order, and when they’re gone the page will just say so.', os: 'no timers. no fake “3 left”.',
      visual: 'Maya draws a flat line in the air — the anti-hype gesture — deadpan', action: 'flat-line draw, deadpan hold', cam: '3Q-SWITCH', comp: 'three-quarter medium' },
    { t: [19, 28], vo: 'First year of Pro for a hundred and ninety dollars, the call included, refund rules printed on the page. If that’s useful, the waitlist is in my bio. If not — the free teardowns continue either way.', os: '$190 first year · terms on the page',
      visual: 'Maya open-palms both hands — the no-pressure gesture — then a genuine nod', action: 'open palms, nod, settle', cam: 'PUSH-IN-SLOW', comp: 'medium close-up' },
  ],
  qcRisks: ['Calendar prop: generated paper text will garble — keep scribbles abstract, or shoot a real calendar insert', 'Open-palms finale — hands', 'Tone check in QC: if any shot reads “salesy”, retake with flatter delivery'],
  thumb: { concept: 'Shot 1 framegrab: calendar to lens', text: '200. here’s why.', source: 'framegrab shot 1', prompt: '' },
  extraRefs: ['Real scribbled wall calendar as phone-shot insert fallback'],
},
];
