// ---------------------------------------------------------------------------
// Content Engine — the Marketing Manager's workspace.
// Shows today's generated content pack, a rolling 14-day calendar, and theme
// performance analysis based on recorded content items.
// ---------------------------------------------------------------------------
import { useState } from 'react';
import { useStore } from '@/store/StoreContext.jsx';
import { generateDailyContent, buildContentCalendar, analyseContentPerformance, THEMES } from '@/ai/marketingManager.js';
import { checkCompliance } from '@/utils/compliance.js';
import { todayISO, formatDate } from '@/utils/dates.js';
import PageHeader from '@/components/layout/PageHeader.jsx';
import Card from '@/components/ui/Card.jsx';
import Button from '@/components/ui/Button.jsx';
import Badge from '@/components/ui/Badge.jsx';
import EmptyState from '@/components/ui/EmptyState.jsx';

/** One block of generated content with a copy button and compliance check. */
function ContentBlock({ label, text }) {
  const [copied, setCopied] = useState(false);
  const { compliant, issues } = checkCompliance(text);
  async function copy() {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // Clipboard unavailable — text can be selected manually.
    }
  }
  return (
    <div className="rounded-lg border border-slate-200 p-3">
      <div className="mb-1.5 flex items-center justify-between gap-2">
        <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p>
        <div className="flex items-center gap-2">
          {compliant ? <Badge tone="green">Compliant ✓</Badge> : <Badge tone="red">Review wording</Badge>}
          <Button size="sm" variant="ghost" onClick={copy}>{copied ? 'Copied ✓' : 'Copy'}</Button>
        </div>
      </div>
      <p className="whitespace-pre-wrap text-sm text-slate-700">{text}</p>
      {!compliant && (
        <ul className="mt-2 list-disc pl-4 text-xs text-rose-600">
          {issues.map((i) => <li key={i}>{i}</li>)}
        </ul>
      )}
    </div>
  );
}

export default function Content() {
  const { state, dispatch } = useStore();
  const today = todayISO();
  const [date, setDate] = useState(today);
  const pack = generateDailyContent(date);
  const calendar = buildContentCalendar(today, 14);
  const performance = analyseContentPerformance(state.contentItems);

  // Log-a-post form state (records published content for performance tracking).
  const [logDraft, setLogDraft] = useState({ title: '', theme: THEMES[0], channel: 'Short-form video', engagements: '', leadsAttributed: '' });

  function logContent(e) {
    e.preventDefault();
    if (!logDraft.title) return;
    dispatch({
      type: 'content/add',
      payload: {
        ...logDraft,
        date: today,
        engagements: Number(logDraft.engagements) || 0,
        leadsAttributed: Number(logDraft.leadsAttributed) || 0,
      },
    });
    setLogDraft({ ...logDraft, title: '', engagements: '', leadsAttributed: '' });
  }

  return (
    <div>
      <PageHeader
        title="Content Engine"
        subtitle="Daily content pack generated by your Marketing Manager — educate first, sell second"
        actions={
          <label className="flex items-center gap-2 text-xs text-slate-500">
            Pack for
            <input type="date" className="field !w-auto" value={date} onChange={(e) => setDate(e.target.value || today)} />
          </label>
        }
      />

      <div className="mb-4 rounded-xl border border-brand-100 bg-brand-50 px-4 py-3 text-sm text-brand-900">
        Theme of the day: <strong>{pack.theme}</strong> · Every draft below passes the compliance guard —
        no approval promises, no guaranteed outcomes. You review and publish; nothing posts automatically.
      </div>

      <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">
        {/* Video ideas */}
        <Card title="Three short-form video ideas">
          <ul className="space-y-2">
            {pack.videoIdeas.map((idea, i) => (
              <li key={i} className="flex gap-2 rounded-lg bg-slate-50 p-3 text-sm text-slate-700">
                <span className="font-bold text-brand-600">{i + 1}.</span> {idea}
              </li>
            ))}
          </ul>
        </Card>

        {/* Social posts */}
        <Card title="Social posts">
          <div className="space-y-3">
            <ContentBlock label="Facebook post" text={pack.facebookPost} />
            <ContentBlock label="LinkedIn post" text={pack.linkedinPost} />
          </div>
        </Card>

        {/* Article + newsletter */}
        <Card title="Educational article">
          <p className="text-sm font-semibold text-slate-800">{pack.article.title}</p>
          <p className="mt-1.5 text-sm text-slate-600">{pack.article.outline}</p>
        </Card>
        <Card title="Email newsletter">
          <ContentBlock label={`Subject: ${pack.newsletter.subject}`} text={pack.newsletter.body} />
        </Card>

        {/* Q&A responses */}
        <Card title="Five responses to common questions">
          <ul className="space-y-3">
            {pack.questionResponses.map((qa, i) => (
              <li key={i}>
                <p className="text-sm font-medium text-slate-800">Q: {qa.question}</p>
                <p className="mt-0.5 text-sm text-slate-600">A: {qa.answer}</p>
              </li>
            ))}
          </ul>
        </Card>

        {/* DM drafts + FAQ */}
        <Card title="Five friendly DM drafts" subtitle="Replace {first} with the person's name">
          <ul className="space-y-2">
            {pack.dmDrafts.map((dm, i) => (
              <li key={i} className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{dm}</li>
            ))}
          </ul>
          <h3 className="mt-4 border-t border-slate-100 pt-3 text-xs font-semibold uppercase tracking-wide text-slate-500">FAQ of the day</h3>
          <p className="mt-2 text-sm font-medium text-slate-800">{pack.faq.question}</p>
          <p className="mt-0.5 text-sm text-slate-600">{pack.faq.answer}</p>
        </Card>

        {/* Calendar */}
        <Card title="14-day content calendar" subtitle="One themed slot per day, channels rotated automatically">
          <div className="overflow-x-auto">
            <table className="w-full min-w-[480px] text-left text-sm">
              <thead>
                <tr className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500">
                  <th className="py-1.5 pr-3">Date</th>
                  <th className="py-1.5 pr-3">Channel</th>
                  <th className="py-1.5">Theme</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {calendar.map((slot) => (
                  <tr key={slot.date} className={slot.date === today ? 'bg-brand-50' : ''}>
                    <td className="py-1.5 pr-3 text-slate-600">{formatDate(slot.date)}</td>
                    <td className="py-1.5 pr-3 text-slate-600">{slot.channel}</td>
                    <td className="py-1.5 text-slate-700">{slot.theme}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>

        {/* Performance */}
        <Card title="Theme performance" subtitle="Log published content below — the Marketing Manager ranks what works">
          {performance.length === 0 ? (
            <EmptyState title="No content logged yet" />
          ) : (
            <ul className="space-y-2">
              {performance.map((t, i) => (
                <li key={t.theme} className="flex items-center justify-between gap-2 text-sm">
                  <span className="text-slate-700">
                    <span className="mr-1.5 font-bold text-brand-600">#{i + 1}</span>{t.theme}
                  </span>
                  <span className="text-xs text-slate-500">
                    {t.posts} post(s) · {t.engagements} engagements · {t.leadsAttributed} lead(s)
                  </span>
                </li>
              ))}
            </ul>
          )}

          <form onSubmit={logContent} className="mt-4 grid grid-cols-2 gap-2 border-t border-slate-100 pt-3">
            <input
              className="field col-span-2"
              placeholder="Title of published content"
              value={logDraft.title}
              onChange={(e) => setLogDraft({ ...logDraft, title: e.target.value })}
            />
            <select className="field" value={logDraft.theme} onChange={(e) => setLogDraft({ ...logDraft, theme: e.target.value })}>
              {THEMES.map((t) => <option key={t}>{t}</option>)}
            </select>
            <select className="field" value={logDraft.channel} onChange={(e) => setLogDraft({ ...logDraft, channel: e.target.value })}>
              {['Short-form video', 'Facebook post', 'LinkedIn post', 'Article', 'Email newsletter', 'Other'].map((c) => <option key={c}>{c}</option>)}
            </select>
            <input
              type="number" min="0" className="field" placeholder="Engagements"
              value={logDraft.engagements}
              onChange={(e) => setLogDraft({ ...logDraft, engagements: e.target.value })}
            />
            <input
              type="number" min="0" className="field" placeholder="Leads attributed"
              value={logDraft.leadsAttributed}
              onChange={(e) => setLogDraft({ ...logDraft, leadsAttributed: e.target.value })}
            />
            <Button type="submit" size="sm" className="col-span-2">Log published content</Button>
          </form>
        </Card>
      </div>
    </div>
  );
}
